' ########################################################################################
' Microsoft Windows
' File: CTOM.inc
' Contents: Classes to work with the Richd Edit Text Object Model (TOM).
' Compiler: FreeBasic 32 & 64-bit
' Copyright (c) 2025 José Roca. Freeware. Use at your own risk.
' THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER
' EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
' MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
' ########################################################################################

#pragma once
#include once "windows.bi"
#include once "win/ole2.bi"
#include once "Afx/CWSTR.inc"
#include once "Afx/AfxTOM.bi"

NAMESPACE Afx

#include once "Afx/CTOMDocument.inc"
#include once "Afx/CTOMRange.inc"
#include once "Afx/CTOMPara.inc"
#include once "Afx/CTOMSelection.inc"
#include once "Afx/CTOMFont.inc"
#include once "Afx/CTOMRow.inc"

END NAMESPACE
